spring:
  application:
    name: ec-app
logging:
  level:
    root: INFO
    com.example.ec: INFO
  file:
    path: logs   # LOG_DIR と揃えるならこちらを基準に

logging:
  structured:
    format:
      console: logstash
      file: logstash

logging:
  structured:
    json:
      stacktrace:
        root: first
        max-length: 1024
        include-common-frames: true
        include-hashes: true

        