spring:
  application:
    name: ec-app
logging:
  level:
    root: INFO
    com.example.ec: INFO
  file:
    path: logs   # LOG_DIR と揃えるならこちらを基準に

logging: 
structured:
format: 
console: logstash

logging: 
structured: 
format: 
file: logstash

logging:
  structured:
    json:
      exclude: log.level
      rename:
        process.id: procid
      add:
        corpname: mycorp

logging:
  structured:
    json:
      stacktrace:
        root: first
        max-length: 1024
        include-common-frames: true
        include-hashes: true